version: '3'

services:
  diatabase:
    container_name: 'diatabase'
    image: 'redis/redis-stack:latest'
    volumes:
      - ../redis-data/diatabase:/data
  diabot:
    container_name: 'diabot'
    image: 'diabot'
    build: .
    ports:
      - '3000:3000'
    restart: on-failure

